### PR TITLE
fix response error and warning controls

### PR DESCRIPTION
**Pull request by ibrahimsag**
Hi,

i guess this is what is meant in the first place.

### CODE REVIEW

**Comment by ibrahimsag** [comment]
@JDBurnZ

**Comment by ibrahimsag** [comment]
Hey @JDBurnZ ,

I talked with @faraday about #11 and added the necessary lines for new release here in this pr. 
I also made a release from my repo(https://pypi.python.org/pypi/pyminfraud/1.0.3). but now it shows my repo as the download url.
To properly handle this,
1. If you agree to these changes, merge this pr.
2. tag the repo with 1.0.3. (`git tag 1.0.3; git push --tags`)
3. then i can push another distribution from this repo so it shows the download url correctly.

wdyt?

**Comment by JDBurnZ** [comment]
Created a 1.0.3 release tagged as 1.0.3.

**Comment by ibrahimsag** [comment]
Hey, 
i messed things up and sent the updated version as 1.0.4 downloading from the 1.0.3 tag. event that doesn't seem right. sorry about that.

Anyways, next release can be 1.0.5. ping me when you need it.

**Comment by JDBurnZ** [comment]
No problem, man.

Thanks for taking the time to get pypi updated!

**Pull request merged**
